"""Sales ORM models — Sale (header) + SaleLine.

A Sale is one transaction at the POS. It can be:

* **cash** (``is_paid=True``, ``paid_amount==total``) — Cash account hit.
* **credit** (``is_paid=False``) — AR account hit, customer required.
* **mixed** — partial paid amount. Remaining sits in AR.
* **service** — non-inventory line (e.g. configure phone). Hits Service
  Revenue instead of Sales Revenue and skips the inventory decrement.

Cost discipline: each ``SaleLine`` snapshots ``cost_snapshot`` at the time
of sale so renaming/repricing the product later never disturbs historical
COGS. Matches the accounting kernel's "ledger is the truth" principle.
"""

from __future__ import annotations

import enum
import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Numeric,
    String,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.db.base import Base, SoftDeleteMixin, TenantScopedMixin, TimestampMixin, uuid_pk


class SaleStatus(str, enum.Enum):
    posted = "posted"          # default — finalized, money + stock moved
    refunded = "refunded"      # fully reversed
    partially_refunded = "partially_refunded"


class Sale(Base, TimestampMixin, SoftDeleteMixin, TenantScopedMixin):
    __tablename__ = "sales"
    __table_args__ = (
        UniqueConstraint("tenant_id", "sale_number", name="uq_sales_tenant_number"),
        CheckConstraint("subtotal >= 0", name="ck_sales_subtotal_nonneg"),
        CheckConstraint("discount_total >= 0", name="ck_sales_discount_nonneg"),
        CheckConstraint("total >= 0", name="ck_sales_total_nonneg"),
        CheckConstraint("paid_amount >= 0", name="ck_sales_paid_nonneg"),
        Index("ix_sales_tenant_date", "tenant_id", "sale_date"),
        Index("ix_sales_tenant_customer", "tenant_id", "customer_id"),
        Index("ix_sales_branch", "branch_id"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()

    # Tenant-scoped sequential number ("INV-000123"). Generated by the
    # service to avoid races (UNIQUE constraint + retry-on-collide).
    sale_number: Mapped[str] = mapped_column(String(30), nullable=False)

    branch_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("branches.id", ondelete="RESTRICT"),
        nullable=False,
    )
    customer_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("customers.id", ondelete="RESTRICT"),
        nullable=True,
    )
    # Free-form name for walk-in customers without a Customer row.
    customer_name: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)

    sale_date: Mapped[date] = mapped_column(Date, nullable=False)

    subtotal: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False, default=Decimal("0"), server_default="0")
    discount_total: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False, default=Decimal("0"), server_default="0")
    total: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False, default=Decimal("0"), server_default="0")
    paid_amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False, default=Decimal("0"), server_default="0")

    is_paid: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, server_default="false")
    status: Mapped[SaleStatus] = mapped_column(
        Enum(SaleStatus, name="sale_status"),
        nullable=False,
        default=SaleStatus.posted,
        server_default=SaleStatus.posted.value,
    )

    notes: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    cashier_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )

    # Each posting writes one of:
    #   - revenue entry (DR Cash/AR / CR Revenue) — always
    #   - COGS entry per inventory line (DR COGS / CR Inventory) — handled
    #     by inventory.decrement_for_sale; we don't store its id on Sale.
    revenue_journal_entry_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("journal_entries.id", ondelete="SET NULL"),
        nullable=True,
    )

    lines: Mapped[list["SaleLine"]] = relationship(
        "SaleLine", back_populates="sale", cascade="all, delete-orphan", lazy="selectin"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Sale {self.sale_number} total={self.total} paid={self.is_paid}>"


class SaleLine(Base, TenantScopedMixin):
    __tablename__ = "sale_lines"
    __table_args__ = (
        CheckConstraint("qty > 0", name="ck_sale_lines_qty_positive"),
        CheckConstraint("unit_price >= 0", name="ck_sale_lines_unit_price_nonneg"),
        CheckConstraint("cost_snapshot >= 0", name="ck_sale_lines_cost_nonneg"),
        Index("ix_sale_lines_sale", "sale_id"),
        Index("ix_sale_lines_product", "product_id"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()

    sale_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("sales.id", ondelete="CASCADE"), nullable=False
    )
    sale: Mapped["Sale"] = relationship("Sale", back_populates="lines")

    # Inventoried sale lines reference a real product. Service lines (e.g.
    # "تركيب شاشة") have product_id = NULL and a free-form description.
    product_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("products.id", ondelete="RESTRICT"),
        nullable=True,
    )
    description: Mapped[str] = mapped_column(String(300), nullable=False)

    qty: Mapped[int] = mapped_column(nullable=False, default=1, server_default="1")

    unit_price: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)
    discount: Mapped[Decimal] = mapped_column(
        Numeric(14, 2), nullable=False, default=Decimal("0"), server_default="0"
    )
    line_total: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)

    # COGS snapshot — what Product.cost was when this line was sold. Used
    # only for reporting / margin analysis; the *actual* COGS journal
    # entry is posted by inventory.decrement_for_sale.
    cost_snapshot: Mapped[Decimal] = mapped_column(
        Numeric(14, 4), nullable=False, default=Decimal("0"), server_default="0"
    )

    # True for service lines (no inventory movement).
    is_service: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )

    # Linked stock movement so the receipt can show "stock was decremented
    # to this exact movement". NULL for service lines.
    stock_movement_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("stock_movements.id", ondelete="SET NULL"),
        nullable=True,
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<SaleLine {self.description} {self.qty}@{self.unit_price}>"


class SalePayment(Base, TimestampMixin, TenantScopedMixin):
    """Debt-collection payment against an existing Sale.

    A credit sale starts with paid_amount = 0 (or partial). Subsequent
    payments append rows here. The accumulated paid_amount on the Sale is
    re-computed by the service after each payment.
    """

    __tablename__ = "sale_payments"
    __table_args__ = (
        CheckConstraint("amount > 0", name="ck_sale_payments_amount_positive"),
        Index("ix_sale_payments_sale", "sale_id"),
        Index("ix_sale_payments_tenant_date", "tenant_id", "payment_date"),
    )

    id: Mapped[uuid.UUID] = uuid_pk()

    sale_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("sales.id", ondelete="RESTRICT"), nullable=False
    )

    amount: Mapped[Decimal] = mapped_column(Numeric(14, 2), nullable=False)
    payment_date: Mapped[date] = mapped_column(Date, nullable=False)
    method: Mapped[str] = mapped_column(
        String(20), nullable=False, default="cash", server_default="cash"
    )  # cash | bank — extend later.
    notes: Mapped[Optional[str]] = mapped_column(String(300), nullable=True)

    received_by_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )

    journal_entry_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("journal_entries.id", ondelete="SET NULL"),
        nullable=True,
    )
