"""initial_schema

Revision ID: c2325ea7abea
Revises: 
Create Date: 2026-05-24 13:20:18.202575

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2325ea7abea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'suspended', 'canceled', name='tenant_status'), server_default='trial', nullable=False),
    sa.Column('default_branch_id', sa.UUID(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('type', sa.Enum('asset', 'liability', 'equity', 'revenue', 'expense', name='account_type'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('system_key', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['accounts.id'], name=op.f('fk_accounts_parent_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_accounts_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_accounts_tenant_code'),
    sa.UniqueConstraint('tenant_id', 'system_key', name='uq_accounts_tenant_system_key')
    )
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_index('ix_accounts_tenant_type', 'accounts', ['tenant_id', 'type'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_branches_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_branches_tenant_code')
    )
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('total_spent_cached', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('debt_cached', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('visits_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_txn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('total_spent_cached >= 0', name=op.f('ck_customers_ck_customers_total_spent_nonneg')),
    sa.CheckConstraint('visits_count >= 0', name=op.f('ck_customers_ck_customers_visits_nonneg')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_customers_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_index('ix_customers_tenant_name', 'customers', ['tenant_id', 'name'], unique=False)
    op.create_index('uq_customers_tenant_email', 'customers', ['tenant_id', 'email'], unique=True, postgresql_where='email IS NOT NULL')
    op.create_index('uq_customers_tenant_phone', 'customers', ['tenant_id', 'phone'], unique=True, postgresql_where='phone IS NOT NULL')
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('mobile', 'accessory', 'spare', 'service', 'other', name='product_category'), server_default='other', nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('reorder_point', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cost >= 0', name=op.f('ck_products_ck_products_cost_nonneg')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_products_ck_products_price_nonneg')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_products_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('tenant_id', 'barcode', name='uq_products_tenant_barcode'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_products_tenant_code')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('total_purchased_cached', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('payable_cached', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('last_txn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('total_purchased_cached >= 0', name=op.f('ck_suppliers_ck_suppliers_total_purchased_nonneg')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_suppliers_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_index('ix_suppliers_tenant_name', 'suppliers', ['tenant_id', 'name'], unique=False)
    op.create_index('uq_suppliers_tenant_email', 'suppliers', ['tenant_id', 'email'], unique=True, postgresql_where='email IS NOT NULL')
    op.create_index('uq_suppliers_tenant_phone', 'suppliers', ['tenant_id', 'phone'], unique=True, postgresql_where='phone IS NOT NULL')
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'accountant', 'cashier', 'technician', 'warehouse_manager', 'viewer', name='user_role'), server_default='cashier', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('default_branch_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_users_tenant_username')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('day_closes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash_in', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash_out', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('counted_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('closed_by_id', sa.UUID(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('counted_cash >= 0', name=op.f('ck_day_closes_ck_day_closes_counted_nonneg')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_day_closes_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], name=op.f('fk_day_closes_closed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_day_closes_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_day_closes')),
    sa.UniqueConstraint('tenant_id', 'branch_id', 'business_date', name='uq_day_closes_tenant_branch_date')
    )
    op.create_index('ix_day_closes_tenant_date', 'day_closes', ['tenant_id', 'business_date'], unique=False)
    op.create_index(op.f('ix_day_closes_tenant_id'), 'day_closes', ['tenant_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('source_ref', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_by_id', sa.UUID(), nullable=True),
    sa.Column('reverses_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_journal_entries_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['posted_by_id'], ['users.id'], name=op.f('fk_journal_entries_posted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reverses_id'], ['journal_entries.id'], name=op.f('fk_journal_entries_reverses_id_journal_entries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_journal_entries_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_entries'))
    )
    op.create_index('ix_journal_entries_branch', 'journal_entries', ['branch_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_branch_id'), 'journal_entries', ['branch_id'], unique=False)
    op.create_index('ix_journal_entries_source', 'journal_entries', ['tenant_id', 'source'], unique=False)
    op.create_index('ix_journal_entries_source_ref', 'journal_entries', ['tenant_id', 'source_ref'], unique=False)
    op.create_index('ix_journal_entries_tenant_date', 'journal_entries', ['tenant_id', 'entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_tenant_id'), 'journal_entries', ['tenant_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_compromised', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_refresh_tokens_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_jti_hash', 'refresh_tokens', ['jti_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_tenant_id'), 'refresh_tokens', ['tenant_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('stock_levels',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('qty_on_hand', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('qty_on_hand >= 0', name=op.f('ck_stock_levels_ck_stock_levels_qty_nonneg')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_levels_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_levels_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stock_levels_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_levels')),
    sa.UniqueConstraint('product_id', 'branch_id', name='uq_stock_levels_product_branch')
    )
    op.create_index('ix_stock_levels_tenant_branch', 'stock_levels', ['tenant_id', 'branch_id'], unique=False)
    op.create_index(op.f('ix_stock_levels_tenant_id'), 'stock_levels', ['tenant_id'], unique=False)
    op.create_index('ix_stock_levels_tenant_product', 'stock_levels', ['tenant_id', 'product_id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('expense_account_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), server_default='cash', nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_ck_expenses_amount_positive')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_expenses_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_expenses_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['accounts.id'], name=op.f('fk_expenses_expense_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_expenses_journal_entry_id_journal_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_expenses_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_account', 'expenses', ['expense_account_id'], unique=False)
    op.create_index('ix_expenses_branch', 'expenses', ['branch_id'], unique=False)
    op.create_index('ix_expenses_tenant_date', 'expenses', ['tenant_id', 'expense_date'], unique=False)
    op.create_index(op.f('ix_expenses_tenant_id'), 'expenses', ['tenant_id'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('(debit > 0 AND credit = 0) OR (debit = 0 AND credit > 0)', name=op.f('ck_journal_lines_ck_journal_lines_debit_xor_credit')),
    sa.CheckConstraint('credit >= 0', name=op.f('ck_journal_lines_ck_journal_lines_credit_nonneg')),
    sa.CheckConstraint('debit >= 0', name=op.f('ck_journal_lines_ck_journal_lines_debit_nonneg')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_journal_lines_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_journal_lines_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], name=op.f('fk_journal_lines_entry_id_journal_entries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_journal_lines_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_journal_lines_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journal_lines'))
    )
    op.create_index('ix_journal_lines_account', 'journal_lines', ['account_id'], unique=False)
    op.create_index('ix_journal_lines_customer', 'journal_lines', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_journal_lines_entry', 'journal_lines', ['entry_id'], unique=False)
    op.create_index('ix_journal_lines_supplier', 'journal_lines', ['tenant_id', 'supplier_id'], unique=False)
    op.create_index('ix_journal_lines_tenant_account', 'journal_lines', ['tenant_id', 'account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_tenant_id'), 'journal_lines', ['tenant_id'], unique=False)
    op.create_table('repair_tickets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ticket_number', sa.String(length=30), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('device_model', sa.String(length=200), nullable=False),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('problem', sa.String(length=500), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('received', 'in_progress', 'done', 'delivered', 'canceled', name='repair_status'), server_default='received', nullable=False),
    sa.Column('date_in', sa.Date(), nullable=False),
    sa.Column('date_delivered', sa.Date(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_paid_on_delivery', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('technician_id', sa.UUID(), nullable=True),
    sa.Column('delivery_journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('actual_cost >= 0', name=op.f('ck_repair_tickets_ck_repair_tickets_actual_nonneg')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_repair_tickets_ck_repair_tickets_estimated_nonneg')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_repair_tickets_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_repair_tickets_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delivery_journal_entry_id'], ['journal_entries.id'], name=op.f('fk_repair_tickets_delivery_journal_entry_id_journal_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], name=op.f('fk_repair_tickets_technician_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_repair_tickets_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repair_tickets')),
    sa.UniqueConstraint('tenant_id', 'ticket_number', name='uq_repair_tickets_tenant_number')
    )
    op.create_index('ix_repair_tickets_branch', 'repair_tickets', ['branch_id'], unique=False)
    op.create_index('ix_repair_tickets_customer', 'repair_tickets', ['customer_id'], unique=False)
    op.create_index('ix_repair_tickets_tenant_date_in', 'repair_tickets', ['tenant_id', 'date_in'], unique=False)
    op.create_index(op.f('ix_repair_tickets_tenant_id'), 'repair_tickets', ['tenant_id'], unique=False)
    op.create_index('ix_repair_tickets_tenant_status', 'repair_tickets', ['tenant_id', 'status'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sale_number', sa.String(length=30), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('posted', 'refunded', 'partially_refunded', name='sale_status'), server_default='posted', nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('cashier_id', sa.UUID(), nullable=True),
    sa.Column('revenue_journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('discount_total >= 0', name=op.f('ck_sales_ck_sales_discount_nonneg')),
    sa.CheckConstraint('paid_amount >= 0', name=op.f('ck_sales_ck_sales_paid_nonneg')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_sales_ck_sales_subtotal_nonneg')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_sales_ck_sales_total_nonneg')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_sales_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], name=op.f('fk_sales_cashier_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revenue_journal_entry_id'], ['journal_entries.id'], name=op.f('fk_sales_revenue_journal_entry_id_journal_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sales_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales')),
    sa.UniqueConstraint('tenant_id', 'sale_number', name='uq_sales_tenant_number')
    )
    op.create_index('ix_sales_branch', 'sales', ['branch_id'], unique=False)
    op.create_index('ix_sales_tenant_customer', 'sales', ['tenant_id', 'customer_id'], unique=False)
    op.create_index('ix_sales_tenant_date', 'sales', ['tenant_id', 'sale_date'], unique=False)
    op.create_index(op.f('ix_sales_tenant_id'), 'sales', ['tenant_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.Enum('purchase', 'return_in', 'transfer_in', 'adjustment_in', 'sale', 'return_out', 'transfer_out', 'adjustment_out', 'repair_consumption', name='movement_type'), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('reverses_id', sa.UUID(), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_stock_movements_ck_stock_movements_qty_positive')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_stock_movements_ck_stock_movements_unit_cost_nonneg')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_stock_movements_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_stock_movements_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_stock_movements_journal_entry_id_journal_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reverses_id'], ['stock_movements.id'], name=op.f('fk_stock_movements_reverses_id_stock_movements'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_stock_movements_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index('ix_stock_movements_reference', 'stock_movements', ['tenant_id', 'reference'], unique=False)
    op.create_index('ix_stock_movements_tenant_branch_date', 'stock_movements', ['tenant_id', 'branch_id', 'movement_date'], unique=False)
    op.create_index(op.f('ix_stock_movements_tenant_id'), 'stock_movements', ['tenant_id'], unique=False)
    op.create_index('ix_stock_movements_tenant_product_date', 'stock_movements', ['tenant_id', 'product_id', 'movement_date'], unique=False)
    op.create_table('sale_lines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('qty', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_snapshot', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('is_service', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('stock_movement_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('cost_snapshot >= 0', name=op.f('ck_sale_lines_ck_sale_lines_cost_nonneg')),
    sa.CheckConstraint('qty > 0', name=op.f('ck_sale_lines_ck_sale_lines_qty_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_sale_lines_ck_sale_lines_unit_price_nonneg')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sale_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_sale_lines_sale_id_sales'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], name=op.f('fk_sale_lines_stock_movement_id_stock_movements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sale_lines_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_lines'))
    )
    op.create_index('ix_sale_lines_product', 'sale_lines', ['product_id'], unique=False)
    op.create_index('ix_sale_lines_sale', 'sale_lines', ['sale_id'], unique=False)
    op.create_index(op.f('ix_sale_lines_tenant_id'), 'sale_lines', ['tenant_id'], unique=False)
    op.create_table('sale_payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=20), server_default='cash', nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_sale_payments_ck_sale_payments_amount_positive')),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], name=op.f('fk_sale_payments_journal_entry_id_journal_entries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], name=op.f('fk_sale_payments_received_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], name=op.f('fk_sale_payments_sale_id_sales'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sale_payments_tenant_id_tenants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sale_payments'))
    )
    op.create_index('ix_sale_payments_sale', 'sale_payments', ['sale_id'], unique=False)
    op.create_index('ix_sale_payments_tenant_date', 'sale_payments', ['tenant_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_sale_payments_tenant_id'), 'sale_payments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_payments_tenant_id'), table_name='sale_payments')
    op.drop_index('ix_sale_payments_tenant_date', table_name='sale_payments')
    op.drop_index('ix_sale_payments_sale', table_name='sale_payments')
    op.drop_table('sale_payments')
    op.drop_index(op.f('ix_sale_lines_tenant_id'), table_name='sale_lines')
    op.drop_index('ix_sale_lines_sale', table_name='sale_lines')
    op.drop_index('ix_sale_lines_product', table_name='sale_lines')
    op.drop_table('sale_lines')
    op.drop_index('ix_stock_movements_tenant_product_date', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_tenant_id'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_tenant_branch_date', table_name='stock_movements')
    op.drop_index('ix_stock_movements_reference', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_sales_tenant_id'), table_name='sales')
    op.drop_index('ix_sales_tenant_date', table_name='sales')
    op.drop_index('ix_sales_tenant_customer', table_name='sales')
    op.drop_index('ix_sales_branch', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_repair_tickets_tenant_status', table_name='repair_tickets')
    op.drop_index(op.f('ix_repair_tickets_tenant_id'), table_name='repair_tickets')
    op.drop_index('ix_repair_tickets_tenant_date_in', table_name='repair_tickets')
    op.drop_index('ix_repair_tickets_customer', table_name='repair_tickets')
    op.drop_index('ix_repair_tickets_branch', table_name='repair_tickets')
    op.drop_table('repair_tickets')
    op.drop_index(op.f('ix_journal_lines_tenant_id'), table_name='journal_lines')
    op.drop_index('ix_journal_lines_tenant_account', table_name='journal_lines')
    op.drop_index('ix_journal_lines_supplier', table_name='journal_lines')
    op.drop_index('ix_journal_lines_entry', table_name='journal_lines')
    op.drop_index('ix_journal_lines_customer', table_name='journal_lines')
    op.drop_index('ix_journal_lines_account', table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_expenses_tenant_id'), table_name='expenses')
    op.drop_index('ix_expenses_tenant_date', table_name='expenses')
    op.drop_index('ix_expenses_branch', table_name='expenses')
    op.drop_index('ix_expenses_account', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_stock_levels_tenant_product', table_name='stock_levels')
    op.drop_index(op.f('ix_stock_levels_tenant_id'), table_name='stock_levels')
    op.drop_index('ix_stock_levels_tenant_branch', table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_tenant_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_jti_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_journal_entries_tenant_id'), table_name='journal_entries')
    op.drop_index('ix_journal_entries_tenant_date', table_name='journal_entries')
    op.drop_index('ix_journal_entries_source_ref', table_name='journal_entries')
    op.drop_index('ix_journal_entries_source', table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_branch_id'), table_name='journal_entries')
    op.drop_index('ix_journal_entries_branch', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_day_closes_tenant_id'), table_name='day_closes')
    op.drop_index('ix_day_closes_tenant_date', table_name='day_closes')
    op.drop_table('day_closes')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('uq_suppliers_tenant_phone', table_name='suppliers', postgresql_where='phone IS NOT NULL')
    op.drop_index('uq_suppliers_tenant_email', table_name='suppliers', postgresql_where='email IS NOT NULL')
    op.drop_index('ix_suppliers_tenant_name', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    op.drop_index('uq_customers_tenant_phone', table_name='customers', postgresql_where='phone IS NOT NULL')
    op.drop_index('uq_customers_tenant_email', table_name='customers', postgresql_where='email IS NOT NULL')
    op.drop_index('ix_customers_tenant_name', table_name='customers')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_branches_tenant_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index('ix_accounts_tenant_type', table_name='accounts')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('tenants')
    # ### end Alembic commands ###
